services:
  algasensors-rabbitmq:
    image: rabbitmq:3-management
    restart: no
    ports:
      - 5673:5672
      - 15673:15672
    environment:
      RABBITMQ_DEFAULT_USER: rabbitmq
      RABBITMQ_DEFAULT_PASS: rabbitmq
    volumes:
      - algasensors-rabbitmq:/var/lib/rabbitmq/
volumes:
  algasensors-rabbitmq: